### ISSUE TITLE
ftx sub account support

### ISSUE THREAD

**Issue by secwang** [vn-crypto/vnpy_ftx#14]
subaccount api can use for connect markets.
buy can't put order. 
need special http header xargs.

SUBACCOUNT="XXX"

**Comment by hall130** [comment]
I have completed this question and adjusted the leverage ratio, but I can't submit

**Comment by hall130** [comment]
我之前参考vnpy_ftx 新增了子账户以及杠杆倍率，子账户已经测试过连接没问题，杠杆倍率还未测试，如果需要https://github.com/hall130/vnpy_ftx/blob/main/ftx_gateway在这个链接

**Comment by meteorliu80** [comment]
@hall130 我自己尝试在网关文件加了子账户，只在FtxRestApi中加了，然后测试了价差和算法交易，都出现了问题，比如持仓未返回，价差只成交了单边等。你这个版本都能解决吗？

**Comment by vn-crypto** [comment]
Since FTX is closed now, I ll just close this issue.
